services:
  - type: web
    name: gen-ai-analytics-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && chmod +x start.sh && ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: CORS_ORIGINS
        value: https://your-frontend-domain.netlify.app
